######### Defines the Load Balancer


apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer     # Exposes Service externally (Cloud IP or Localhost)
  selector:
    app: my-nginx-app    # Selects pods from the Deployment above
  ports:
    - port: 80           # Port exposed to the public
      targetPort: 80     # Port the container listens on